default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host:  <%= ENV.fetch('DATABASE_HOST') %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>

development:
  <<: *default

test:
  <<: *default
  database: todo_list_hotwire_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
